// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Login struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Message struct {
	ID   string    `json:"id"`
	Text string    `json:"text"`
	Date time.Time `json:"date"`
	User *User     `json:"user"`
}

type NewMessage struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type NewUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
