version: "3.8"

services:
  database:
    container_name: database
    image: postgres:15.1
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=messenger
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/db
volumes:
  db: